# Введение в NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # создаёт объект типа ndarray

In [3]:
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
print(b)
print(b[0, 1])
print(b[1, 2])
# То есть [[первая строка]
#          [вторая строка]]

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
2.0
6.0


In [5]:
d = np.array([[(1.5, 2, 3), (4, 5, 6)], [(7, 8, 9), (11, 12, 10)]])
print(d)
# 3D массив 

[[[  1.5   2.    3. ]
  [  4.    5.    6. ]]

 [[  7.    8.    9. ]
  [ 11.   12.   10. ]]]


#### Массив любой размерности указываем в [ ]

In [6]:
print(np.zeros((3, 5)))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [7]:
print(np.ones((2, 2, 2)))

[[[ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]]


In [8]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [9]:
np.empty((3, 4)) # исходное содержимое случайно и зависит
# состояния памяти, на момент создания массива

array([[  1.5,   2. ,   3. ,   4. ],
       [  5. ,   6. ,   7. ,   8. ],
       [  9. ,  11. ,  12. ,  10. ]])

### Создание последовательностей

In [11]:
# arange ~ rangeв Python, но создаёт массив
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [12]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

Из-за ограничений точности чисел с плавающей точкой нельзя быть уверенным сколько чисел будет получено в np.arange при использовании нецелых значений.
Поэтому в такиих случаях лучше использовать linspace(), которая вместо шага принимает число, равное количеству нужных элементов.

In [15]:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [23]:
print(np.linspace(0, 10, 8))
print('-'*100)
print(np.linspace(0, 10, 9))
print('-'*100)
print(np.linspace(0, 10, 10))
print('-'*100)
print(np.linspace(0, 10, 11))

[  0.           1.42857143   2.85714286   4.28571429   5.71428571
   7.14285714   8.57142857  10.        ]
----------------------------------------------------------------------------------------------------
[  0.     1.25   2.5    3.75   5.     6.25   7.5    8.75  10.  ]
----------------------------------------------------------------------------------------------------
[  0.           1.11111111   2.22222222   3.33333333   4.44444444
   5.55555556   6.66666667   7.77777778   8.88888889  10.        ]
----------------------------------------------------------------------------------------------------
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [24]:
def f1(i, j):
    return 3 * i + j

In [26]:
np.fromfunction(f1, (3, 3))

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

## Операции над массивами

МАТЕМАТИЧЕСКИЕ и ЛОГИЧЕСКИЕ операции над массивами выполняются поэлементрно, в результате СОЗДАЁТСЯ НОВЫЙ МАССИВ.

In [34]:
a = np.array([[20, 30, 40, 50], [2, 3, 4, 5]])
b = np.random.randint(10, size=(2, 4))

In [35]:
print(a)
print(b)

[[20 30 40 50]
 [ 2  3  4  5]]
[[4 3 1 6]
 [0 6 8 1]]


In [36]:
a - b

array([[16, 27, 39, 44],
       [ 2, -3, -4,  4]])

In [37]:
a + b

array([[24, 33, 41, 56],
       [ 2,  9, 12,  6]])

In [38]:
a * b

array([[ 80,  90,  40, 300],
       [  0,  18,  32,   5]])

In [41]:
a / b
# При делении на 0 возвразает бескоечность

C:\Users\Zhenia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[  5.        ,  10.        ,  40.        ,   8.33333333],
       [         inf,   0.5       ,   0.5       ,   5.        ]])

In [43]:
a % b
# при взятии остатка от деленеия на 0 возвращает 0

C:\Users\Zhenia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0, 0, 2],
       [0, 3, 4, 0]], dtype=int32)

In [44]:
a == b

array([[False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [45]:
a < b

array([[False, False, False, False],
       [False,  True,  True, False]], dtype=bool)

In [46]:
b < a

array([[ True,  True,  True,  True],
       [ True, False, False,  True]], dtype=bool)

In [47]:
a

array([[20, 30, 40, 50],
       [ 2,  3,  4,  5]])

In [49]:
a + 5

array([[25, 35, 45, 55],
       [ 7,  8,  9, 10]])

In [50]:
np.add(a, 5)

array([[25, 35, 45, 55],
       [ 7,  8,  9, 10]])

In [52]:
a

array([[20, 30, 40, 50],
       [ 2,  3,  4,  5]])

Имеется множество функций для обработки массивов (cos, tg, ....)

In [55]:
print(a.sum())
print(a.max())
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

154
50
[ 11.   16.5  22.   27.5]
[ 35.    3.5]


In [61]:
a = a.T
a

array([[20,  2],
       [30,  3],
       [40,  4],
       [50,  5]])

In [62]:
a.shape

(4, 2)

In [63]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [65]:
a = a.T
np.log(a)

array([[ 2.99573227,  3.40119738,  3.68887945,  3.91202301],
       [ 0.69314718,  1.09861229,  1.38629436,  1.60943791]])

Осуществляют срезы, индексы и итерации как списки Python, 
но являются неизменяемыми, поэтому просто возвращают новый массив. Нельзя удалить с помощьюсрезов.

In [66]:
a

array([[20, 30, 40, 50],
       [ 2,  3,  4,  5]])

In [67]:
a[1,2]

4

In [70]:
a[1, 1:2]

array([3])

In [71]:
a[1, 1:5]

array([3, 4, 5])

In [72]:
a

array([[20, 30, 40, 50],
       [ 2,  3,  4,  5]])

In [89]:
b = np.array([1,2,3,4,5])

In [90]:
b

array([1, 2, 3, 4, 5])

In [91]:
c = b[0:5]
c

array([1, 2, 3, 4, 5])

In [92]:
b

array([1, 2, 3, 4, 5])

In [93]:
b = b + c
b

array([ 2,  4,  6,  8, 10])

In [94]:
b = b + b[1:5]

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [95]:
a

array([[20, 30, 40, 50],
       [ 2,  3,  4,  5]])

In [96]:
for row in a:
    print(row)

[20 30 40 50]
[2 3 4 5]


# Введение в MatPlotLib